### ISSUE TITLE
[Remontée numéro de version] Vincent

### ISSUE THREAD

**Issue by vferries** [89C3-anim/Meetup-front#1]
## Description du sujet

Comment inclure des ajouts dans la gestion des versions npm (retrouver son numéro de version dans son appli par exemple).

---

## Miscs

* Il s'agit :
    - [x] D'une proposition de conférence
    - [ ] D'une demande de conférence
* Tags (e.g: angular, redux...) :
* Niveau de difficulté :
    - [x] débutant
    - [ ] avancé
    - [ ] expert
* Durée (max 45 min) : 5 min
* Format:
    - [ ] Slides
    - [x] Live coding
    - [ ] Vidéo
* Disponibilité (e.g: ASAP, avant/après XXX): Quand on veut

**Comment by belamrani** [comment]
@vferries tu peux fermer please.
