### ISSUE TITLE
[ Retours NG-Europe ] 

### ISSUE THREAD

**Issue by belamrani** [89C3-anim/Meetup-front#10]
Retours sur la conférence NG-Europe qui a eu lieu le 2 février à Paris. 

## Description du sujet

---

## Miscs

* Il s'agit :
    - [ ] D'une proposition de conférence
    - [X] D'une demande de conférence
* Tags (e.g: angular, redux...) :
* Niveau de difficulté :
    - [ ] débutant
    - [ ] avancé
    - [ ] expert
* Durée (max 45 min) : 
* Format:
    - [ ] Slides
    - [ ] Live coding
    - [ ] Vidéo
* Disponibilité (e.g: ASAP, avant/après XXX): Pour le 23 février si vous avez le temps ?

**Comment by timurrustamov** [comment]
Les videos de ng-europe 2018 sont disponibles ;)
https://www.youtube.com/watch?v=NbJonysf45Q&list=PLhc_bKwZngxVQZtyPzGY9dRJOnGP1xVVX

**Comment by belamrani** [comment]
top :) merci Timur.
