### ISSUE TITLE
[JSX, CSSinJS, SSR - It's all just Javascript*] Timur Rustamov

### ISSUE THREAD

**Issue by timurrustamov** [89C3-anim/Meetup-front#13]
## Description du sujet

Dernièrement nous pouvons constater, une tendance vers unification et componentisation (ouf ce barbarisme) des différents aspects d'une RIA, mais qu'en est il réellement?
Nous allons voir ensemble les équivalents des templates HTML, de CSS et de server-side rendering* (si l'on considère que Apache fait du SSR 😛) vers le Javascript ainsi que leurs avantages et inconvénients. 

Dans le programme:
- Introduction au JSX avec l'incontournable [react](https://reactjs.org/), le petit [hyperapp](https://hyperapp.js.org/), et ce mix de react et angular qui est [stencil.js](https://stenciljs.com/).
- Introduction au CSSinJS - le precurseur [css-modules](https://github.com/css-modules/css-modules), le hyped [styled-components](https://www.styled-components.com/), et mon petit préféré - [jss](https://github.com/cssinjs/jss).
- Introduction au [Next.js](https://github.com/zeit/next.js/).

Voila un peu le scope du talk, peut etre il est un poil trop large non? Dites-moi! On pourrait peut être se concentrer d'avantage sur le JSX et CSSinJS et drop le SSR, je sais pas, ou même éviter de rentrer dans les libs et discuter juste de la philosophie et des réponses aux différentes problématiques par ces solutions innovantes.

Voila voila! 😅

---

## Miscs

* Il s'agit :
    - [x] D'une proposition de conférence
    - [ ] D'une demande de conférence
* Tags (e.g: angular, redux...) :
* Niveau de difficulté :
    - [x] débutant
    - [ ] avancé
    - [ ] expert
* Durée (max 45 min) : 
* Format:
    - [x] Slides
    - [x] Live coding
    - [ ] Vidéo
* Disponibilité (e.g: ASAP, avant/après XXX): ASAP

**Comment by choucry13** [comment]
j'adore le concept :-)

**Comment by timurrustamov** [comment]
Ce talk aura lieu le vendredi 27 avril ;)
