### ISSUE TITLE
[Introduction à Rxjs v6 avec un petit questionnaire interactif Pas piqué comme des hannetons] by SAS Philippe Beroucry

### ISSUE THREAD

**Issue by choucry13** [89C3-anim/Meetup-front#17]
## Description du sujet
Hello les amis, avec l'arrivé de la v6 d'Angular, rxjs a également fait évolution sa lib. L'idée c'est de vous montrer les principaux changements dessus. On va s'intéresser à plusieurs choses dont : les pipes, les imports et bien d'autres .....

---

## Miscs

* Il s'agit :
    - [X] D'une proposition de conférence
    - [ ] D'une demande de conférence
* Tags (e.g: angular, redux...) :
* Niveau de difficulté :
    - [X] débutant
    - [X] avancé
    - [ ] expert
* Durée (max 45 min) : 20 minutes
* Format:
    - [X] Slides
    - [X ] Live coding
    - [ ] Vidéo
* Disponibilité (e.g: ASAP, avant/après XXX): mi juin 2018

**Comment by belamrani** [comment]
Excellente idée !! bon courage pour piéger Thomas par contre :)

**Comment by ThomasSalvetat** [comment]
xD
Mais non tkt ... :p 
Par contre j'espère que tu nous convaincra au sujet des pipes :+1

**Comment by choucry13** [comment]
@belamrani , @ThomasSalvetat , vous m'avez tué :-)
