### ISSUE TITLE
[CSS in JS] Timur Rustamov

### ISSUE THREAD

**Issue by timurrustamov** [89C3-anim/Meetup-front#18]
## Description du sujet

On a parlé de la facon dont on utilisait le CSS dans nos applications depuis 1994, et comment on l'utilise ne 2018 et des avantages et inconvenients du CSS in JS. Deux libs sont mises en lumiere - le [styled-jsx](https://github.com/zeit/styled-jsx) et [styled-components](https://www.styled-components.com/).

---

## Miscs

* Il s'agit :
    - [x] D'une proposition de conférence
    - [ ] D'une demande de conférence
* Tags (e.g: angular, redux...) :
* Niveau de difficulté :
    - [x] débutant
    - [ ] avancé
    - [ ] expert
* Durée (max 45 min) : 20 min
* Format:
    - [x] Slides
    - [x] Live coding
    - [ ] Vidéo
* Disponibilité (e.g: ASAP, avant/après XXX):

**Comment by belamrani** [comment]
Merci Timur 👍
